"""First test migration

Revision ID: 10280b81d29a
Revises:
Create Date: 2022-09-15 23:37:54.856630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10280b81d29a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=30), nullable=False),
        sa.Column('lastname', sa.String(), nullable=True),
        sa.Column('tg_username', sa.String(length=30), nullable=True),
        sa.Column('tg_chat_id', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'event',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('event_type', sa.String(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    op.drop_table('users')
    # ### end Alembic commands ###
