"""remake tg_chat_id to BigInteger

Revision ID: 20c59fba0499
Revises: e47e442b28ca
Create Date: 2022-09-20 14:17:48.476315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20c59fba0499'
down_revision = 'e47e442b28ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
