"""remake tg_chat_id to BigInteger

Revision ID: 3ffcad37a680
Revises: c9d7882c5456
Create Date: 2022-09-20 13:55:07.856292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ffcad37a680'
down_revision = 'c9d7882c5456'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
