"""make tg_username field unique

Revision ID: 829d09c6d0c4
Revises: e7c2f91b83cb
Create Date: 2022-09-18 22:31:42.557038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '829d09c6d0c4'
down_revision = 'e7c2f91b83cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['tg_username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
