"""make tg_username field not unique because it can be None

Revision ID: c9d7882c5456
Revises: 829d09c6d0c4
Create Date: 2022-09-19 01:17:11.683835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9d7882c5456'
down_revision = '829d09c6d0c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_tg_username_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_tg_username_key', 'users', ['tg_username'])
    # ### end Alembic commands ###
