"""remake tg_chat_id to BigInteger

Revision ID: e47e442b28ca
Revises: 3ffcad37a680
Create Date: 2022-09-20 13:57:27.881348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e47e442b28ca'
down_revision = '3ffcad37a680'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
